[ERROR] [2017-01-19 13:59:13,686] [org.hibernate.tool.hbm2ddl.SchemaUpdate] could not get database metadata
java.sql.SQLException: Access denied for user 'admin'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:133)
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.prepare(SuppliedConnectionProviderConnectionHelper.java:51)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:168)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:375)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1845)
	at com.util.hibernate.HibernateUtil.<clinit>(HibernateUtil.java:22)
	at com.util.hibernate.Transaction.begin(Transaction.java:15)
	at com.Msg03Resender.main(Msg03Resender.java:22)
[ERROR] [2017-01-19 13:59:13,689] [org.hibernate.tool.hbm2ddl.SchemaUpdate] could not complete schema update
java.sql.SQLException: Access denied for user 'admin'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:133)
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.prepare(SuppliedConnectionProviderConnectionHelper.java:51)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:168)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:375)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1845)
	at com.util.hibernate.HibernateUtil.<clinit>(HibernateUtil.java:22)
	at com.util.hibernate.Transaction.begin(Transaction.java:15)
	at com.Msg03Resender.main(Msg03Resender.java:22)
[ERROR] [2017-01-19 13:59:13,807] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'admin'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:14,323] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'admin'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:14,830] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'admin'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:15,336] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'admin'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:15,839] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'admin'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:16,344] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'admin'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:16,846] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'admin'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:17,353] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'admin'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:17,868] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'admin'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:18,385] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'admin'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:18,888] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'admin'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:19,393] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'admin'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:19,895] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'admin'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:32,111] [org.hibernate.tool.hbm2ddl.SchemaUpdate] could not get database metadata
java.sql.SQLException: Access denied for user 'zmc'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:133)
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.prepare(SuppliedConnectionProviderConnectionHelper.java:51)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:168)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:375)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1845)
	at com.util.hibernate.HibernateUtil.<clinit>(HibernateUtil.java:22)
	at com.util.hibernate.Transaction.begin(Transaction.java:15)
	at com.Msg03Resender.main(Msg03Resender.java:22)
[ERROR] [2017-01-19 13:59:32,113] [org.hibernate.tool.hbm2ddl.SchemaUpdate] could not complete schema update
java.sql.SQLException: Access denied for user 'zmc'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:133)
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.prepare(SuppliedConnectionProviderConnectionHelper.java:51)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:168)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:375)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1845)
	at com.util.hibernate.HibernateUtil.<clinit>(HibernateUtil.java:22)
	at com.util.hibernate.Transaction.begin(Transaction.java:15)
	at com.Msg03Resender.main(Msg03Resender.java:22)
[ERROR] [2017-01-19 13:59:32,189] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'zmc'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:32,698] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'zmc'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:33,207] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'zmc'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:33,714] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'zmc'@'localhost' (using password: YES)
[ERROR] [2017-01-19 13:59:34,222] [org.hibernate.util.JDBCExceptionReporter] Access denied for user 'zmc'@'localhost' (using password: YES)
[ERROR] [2017-01-19 16:40:28,099] [com.asrs.communication.ConnectionManager] 无法连接BL01
[ERROR] [2017-01-19 16:40:29,172] [com.asrs.communication.ConnectionManager] 无法连接MC01
[ERROR] [2017-01-19 16:40:29,190] [com.asrs.communication.PlcConnection] 
[ERROR] [2017-01-19 16:40:29,195] [com.asrs.communication.PlcConnection] SendHandler被中断
[ERROR] [2017-01-19 16:40:30,210] [com.asrs.communication.ConnectionManager] 无法连接SC01
[ERROR] [2017-01-19 16:40:31,270] [com.asrs.communication.ConnectionManager] 无法连接SC02
[ERROR] [2017-01-19 16:40:37,318] [com.asrs.communication.ConnectionManager] 无法连接MC01
